//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class D1Entities : DbContext
    {
        public D1Entities()
            : base("name=D1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_login> Admin_login { get; set; }
        public virtual DbSet<MVCregUser> MVCregUsers { get; set; }
        public virtual DbSet<occupation_table> occupation_table { get; set; }
        public virtual DbSet<User_login> User_login { get; set; }
    
        public virtual ObjectResult<D2_Result> D2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<D2_Result>("D2");
        }
    
        public virtual ObjectResult<Nullable<int>> LoginCheck(string user_Name, string password)
        {
            var user_NameParameter = user_Name != null ?
                new ObjectParameter("User_Name", user_Name) :
                new ObjectParameter("User_Name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginCheck", user_NameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<tracker3_Result> tracker3(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tracker3_Result>("tracker3", iDParameter);
        }
    
        public virtual ObjectResult<tracker4_Result> tracker4(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tracker4_Result>("tracker4", iDParameter);
        }
    
        public virtual ObjectResult<loantrackeredit_Result> loantrackeredit(Nullable<int> iD, Nullable<decimal> mobileNo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loantrackeredit_Result>("loantrackeredit", iDParameter, mobileNoParameter);
        }
    }
}
