//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCregUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVCregUser()
        {
            this.occupation_table = new HashSet<occupation_table>();
        }
    
        public int ID { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        
        public Nullable<decimal> MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Pincode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<occupation_table> occupation_table { get; set; }
    }
}
