//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class occupation_table
    {
        public int Occ_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Occ_type { get; set; }
        public string Designation { get; set; }
        public Nullable<long> Gross_income { get; set; }
        public Nullable<long> Adharcard_No { get; set; }
        public string Pancard_No { get; set; }
        public Nullable<long> Loan_amount { get; set; }
        public Nullable<int> Tensure { get; set; }
    
        public virtual MVCregUser MVCregUser { get; set; }
    }
}
