// <auto-generated />
namespace FlightReservationProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcoll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcoll));
        
        string IMigrationMetadata.Id
        {
            get { return "202106282122067_add-coll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
