//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;


    public partial class NewAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewAcc()
        {
            this.AccountMasters = new HashSet<AccountMaster>();
            this.Logins = new HashSet<Login>();
        }
    
        public decimal CustId { get; set; }
        [DisplayName("Title(Mr/Mrs/Ms)")]
        [Required]
        public string Title { get; set; }
        [DisplayName("FirstName")]
        [Required]

        public string Fname { get; set; }
        [DisplayName("LastName")]
        [Required]
        public string Lname { get; set; }
        [DisplayName("MobileNumber")]
        [Required]
        public Nullable<decimal> Phone { get; set; }
        [DisplayName("EmailId")]
        [Required]
        public string Email { get; set; }
        [DisplayName("PANNumber")]
        [Required]
        public string PAN { get; set; }
        [DisplayName("AadharNumber")]
        [Required]
        public Nullable<decimal> Aadhar { get; set; }
        [DisplayName("DateofBirth")]
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime DOB { get; set; }
        [DisplayName("AddressLine1")]
        [Required]
        public string ResAdd { get; set; }
        [DisplayName("BranchName")]
        [Required]
        public string BranchName { get; set; }
        [DisplayName("City")]
        [Required]
        public string City { get; set; }
        [DisplayName("Pincode")]
        [Required]
        public Nullable<decimal> Pincode { get; set; }
        [DisplayName("State")]
        [Required]
        public string State { get; set; }
        [DisplayName("AddressLine1")]
        [Required]
        public string PerAdd { get; set; }
        [DisplayName("AddressLine2")]
        [Required]
        public string PerAdd1 { get; set; }
        [DisplayName("City")]
        [Required]
        public string City01 { get; set; }
        [DisplayName("Pincode")]
        [Required]
        public Nullable<decimal> pincode01 { get; set; }
        [DisplayName("State")]
        [Required]
        public string state01 { get; set; }
        [DisplayName("Gender")]
        [Required]
        public string Gender { get; set; }
        [DisplayName("Occupation")]
        [Required]
        public string Occupation { get; set; }
        [DisplayName("Income")]
        [Required]
        public Nullable<decimal> Income { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMaster> AccountMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
    }
}
